# Generated by Django 3.2 on 2024-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.TextField(),
        ),
    ]
