# Generated by Django 3.2 on 2024-05-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_medication_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='audio',
            field=models.FileField(default=1, upload_to='medications/'),
            preserve_default=False,
        ),
    ]
