# Generated by Django 3.2 on 2024-05-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_medication_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='audio',
            field=models.FileField(upload_to='audios/'),
        ),
    ]
