# Generated by Django 3.2 on 2024-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_medication_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='reminder_time',
            field=models.TextField(verbose_name='提醒时间'),
        ),
    ]
