# Generated by Django 3.2 on 2024-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_medication_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='username',
            field=models.TextField(verbose_name='被提醒用户名'),
        ),
    ]
